# Generated by Django 3.2 on 2023-06-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addr',
            options={'verbose_name': '收货表', 'verbose_name_plural': '收货表'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '地域表', 'verbose_name_plural': '地域表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='verifcode',
            options={'verbose_name': '验证码表', 'verbose_name_plural': '验证码表'},
        ),
    ]
